package test

import (
	"fmt"
	tbox "github.com/redrain-wang/golang-toolbox"
	"testing"
)

// all time tools function example
func TestTime(t *testing.T) {
	fmt.Println(tbox.GetNowString())
	fmt.Println(tbox.GetTimeZone())
	fmt.Println(tbox.TransTimeStringToGoTime("2019-11-15 11:17:23"))
	fmt.Println(tbox.TransTimeStringByFormatToGoTime("2006-01-02 15:04", "2019-11-15 11:17"))
	fmt.Println(tbox.GetYear())
	fmt.Println(tbox.GetYearByFormatTime("2006-01-02 15:04", "2019-11-15 11:17"))
	fmt.Println(tbox.GetYearStringByFormatTime("2006-01-02 15:04:05", "2008-08-08 08:08:08"))
	fmt.Println(tbox.GetYearString())
	fmt.Println(tbox.GetMonthString())
	fmt.Println(tbox.GetMonthNumber())
	fmt.Println(tbox.GetMonthChina())
	fmt.Println(tbox.GetMonthChinaByNum(int(tbox.GetMonthNumber())))
	fmt.Println(tbox.GetDay())
	fmt.Println(tbox.GetHour())
	fmt.Println(tbox.GetMinute())
	fmt.Println(tbox.GetSecond())
	fmt.Println(tbox.GetMillSecond())
	fmt.Println(tbox.GetNanoSecond())
	fmt.Println(tbox.GetTodayDate())
	fmt.Println(tbox.GetCurrentTime())
	fmt.Println(tbox.GetTimestampSecond())
	fmt.Println(tbox.GetTimestampMill())
	fmt.Println(tbox.GetTimestampMico())
	fmt.Println(tbox.GetTimeStampNano())
	fmt.Println(tbox.GetThDayInYear())
	fmt.Println(tbox.GetThDayInMonth())
	fmt.Println(tbox.GetWeekEnglish())
	fmt.Println(tbox.GetWeekInt())
	fmt.Println(tbox.GetWeekChina())
	fmt.Println(tbox.GetFirstDayWeekOfYear())
	fmt.Println(tbox.GetFirstWeekDayCountsOfYear())
	fmt.Println(tbox.GetWeekThOfYear())
	fmt.Println(tbox.GetWeekThOfYearByTime(tbox.TransTimeStringToGoTime("2019-01-01 11:17:23")))
	fmt.Println(tbox.GetFirstDayDateOfMonth())
	fmt.Println(tbox.GetLastDayDateOfMonth())
	fmt.Println(tbox.GetDayCountsOfMonth())
	fmt.Println(tbox.GetFirstDayWeekOfMonth())
	fmt.Println(tbox.GetFirstWeekDayCountsOfMonth())
	fmt.Println(tbox.GetWeekThOfMonth())
	fmt.Println(tbox.GetCurrentTimeAddDays(1))
	fmt.Println(tbox.GetCurrentTimeAddSeconds(3600))
	fmt.Println(tbox.GetCurrentTimeAddSecondsString(3600))
	fmt.Println(tbox.GetCurrentTimeAddMonths(2))
	fmt.Println(tbox.GetTimeStringByUnixTime(tbox.GetNow().Unix()))
	fmt.Println(tbox.GetTimeDiffSecond(tbox.GetNowString(), "2019-01-01 11:57:20"))
	fmt.Println(tbox.GetTimeDiffMinute(tbox.GetNowString(), "2019-01-01 11:57:20"))
	fmt.Println(tbox.IsMonday())
	fmt.Println(tbox.IsTuesday())
	fmt.Println(tbox.IsWednesday())
	fmt.Println(tbox.IsThursday())
	fmt.Println(tbox.IsFriday())
	fmt.Println(tbox.IsSaturday())
	fmt.Println(tbox.IsCurrentYear("2019-11-27 12:12:12"))
	fmt.Println(tbox.IsLastYear("2019-11-27 12:12:12"))
	fmt.Println(tbox.IsNextYear("2019-11-27 12:12:12"))

}
